### ISSUE TITLE
Watch improvements for many nodes

### ISSUE THREAD

**Issue by Aestek** [hashicorp/go-memdb#51]
This is a follow-up of https://github.com/hashicorp/consul/issues/4984

### Recap 
memdb provides a `WatchSet.AddWithLimit(limit, nodeCh, fallbackNodeCh)` feature that falls back to a higher (in the tree hierarchy) node if > limit nodes are watched. This mechanism bounds the number of goroutines used to watch a set of nodes.
Consul sets this limit to 2048 currently on master. When watching service nodes fore example the fallback is the root of all nodes. As described in the linked issue switching to this fallback greatly decreases performance as the root node constantly changes.
We'd like to increase this limit while still keeping the number of G under control.

### Proposition 1
`aFew` is currently set to 32. We could selectively use a bigger `select{}` based on the number of channels to watch. My very early benchmarks show that performance is decent with aFew up to 128, it decreases rapidly after that.
This allows to cut the number by ~4, however it doesn't scale well.

### Proposition 2
This is untested/unbenchmarked yet.
Currently each radix node has a ch that gets closed when a change occurs. `WatchSet.Watch()` blocks on these chs.
We could reverse this mechanism by having a slice of chs in each node. WatchSet would have a single ch, add it to each watched node on `Add()` and then block on this single ch on `Watch()`. On change, each of the node chs would be closed.
While being intrusive, this would allow to watch many many nodes with no additional G. Note that the two mechanisms could cohabit during the transition with the nodes holding both their current WatchCh and a slice, and two WatchSet implementations.

What do you think ?

/cc @banks @pierresouchay

**Comment by banks** [comment]
Hey @Aestek 

I've given this a lot of thought as it's important to Consul and feeds into other work we need to do on Scaling.

On the face of it your second proposition sounds really compelling... in practice though the logic around tracking merging etc mutateChs is pretty well spread deep within `iradix` (not this lib) which would make it extremely hard to move to a model where each radix node has a set of subscriber chans rather than a single one. Take a look at the examples here to get a feel for how much complication that would add:

https://github.com/hashicorp/go-immutable-radix/blob/7f3cd4390caab3250a57f30efdb2a65dd7649ecf/iradix.go#L100

e.g. every internal radix tree merge during a mutation currently tracks the channel of the node being merged: https://github.com/hashicorp/go-immutable-radix/blob/7f3cd4390caab3250a57f30efdb2a65dd7649ecf/iradix.go#L213

It's possible but a pretty large change. Not to mention that the external API would be inverted too.

But that's not all, in order not to leak memory if a watched node _doesn't_ change for the dureation of a blocking query in Consul, we'd need a way to go back an unsubscribe the query's chan from every node it watched.

On top of that, how would notification work? For example if one blocking query watched 2 different radix nodes and they both changed in a transaction, `Notify()` would go to the first, iterate it's watchers and close their chans, then it would go to  node 2 and start to close the chans there, but one of them is the same chan it just closed so closing it will panic!

In practice, the blocking goroutine would have been unblocked by the first close and will eventually deregister all it's other subscriptions in the radix tree, but that will race with notify loop.

## Alternative Proposal

Instead of those deep changes, I think we can solve all the above issues and require _zero_ goroutines just watching channels for arbitrarily large queries and numbers of subscribers.

It works like this:
 - Add a new method to `iradix` like `NotifyBulk(o ObserverFn)` it can only be used _instead_ of `Notify` when using `CommitOnly` (as memdb does in general).
   - It does the same logic as `Notify` including `notifySlow` case, but _as well_ as closing each mutateCh, it also appends a pointer to the node to `[]<-chan struct{}`. I'll call this a `MutationBatch`.
   - The `ObserverFn` is just invoked with complete `MutationBatch`
   - The `ObserverFn` doesn't use the chans as chans at all (they are already closed after all) but can just use them as unique identifiers for the nodes that have changed. We could instead return a list of node pointers in the batch but then we'd need to hand out the same pointers to live nodes when doing queries which is really gross and could allow callers to corrupt the datastructure. We could add another field just as a unique ID too but this mechanism although a bit hacky works fine with no additional memory needed.
 - In MemDB or in Consul first we can now build a shared `WatchPool` which each blocking query can use to register its interest in a given watchChan like `pool.Subscribe(iter.WatchCh(), notifyCh)`. This just registers the watchedCh _as an identifier_ in adds the `notifyCh` to the set of subscribers for that `watchCh` (like you are proposing here)
 - A `memdb.Txn` could now have a single `ObserverFn` registered and if so then it uses `NotifyBulk` instead. This may be called multiple times in a single Txn commit since multiple iradix tables might be updated but that doesn't really matter since all tables commit before any are notified.
 - memdb/consul could in their `ObeserverFn` just loop through the `MutateBatch` of chans and for each one call `pool.Trigger(ch)` which will close all the subscribing chans and trigger them.

Benefits of this approach:

 - WatchPool is very like your solution but can be decoupled from `iradix` and even from `MemDB` at first.
 - A variant of WatchPool can be implemented with only Consul changes and gets most of the benefit for scaling to many subscribers even without `NotifyBulk` because the same radix nodes can be watched in one place (similar to your sharedBlocking PR but a lower level so less work to integrate I think). That would still need a goroutine per node watched but be constant for N subscribers. We can optimise it with the mechanism here later without changing the usage too.
 - If we made the full zero-goroutine version above, only changes needed in `iradix` are a new Notify method and no changes to the core update algorithms or data structure or interface.
 - Callers still use the same interface except using a special `watchpool.WatchSet` which interacts with the `WatchPool` described above but otherwise has the same external interface as `memdb.WatchSet`.

A super quick and 100% untested `WatchPool` can be seen here: https://gist.github.com/banks/1196bbddbd5fe561f2aef71aec6a40c5

That version would be possible to use in Consul now and doesn't rely on MemDB/iradix changes I described here, but I think could benefit from them later (would become zero-goroutines to maintain watches!).

What do you think?

**Comment by Aestek** [comment]
@banks ,

Tanks for taking the time to look into this :)

If I understood correctly, the change you are proposing uses the same goroutines for all the watches needed by blocking queries on the radix, hence instead of having `N =  (requests * (watched_nodes / 32)` we would have just  `N =  (watched_nodes / 32)` ?
That sounds like a great optimization for memdb !

However for Consul I feel this is already addressed (albeit not as much) by https://github.com/hashicorp/consul/pull/5050. 
The two could of course be combined for maximal performance >:D 

Regards

**Comment by banks** [comment]
Actually my proposal above is a little different to what you described.

As proposed including memdb changes, you would end up with zero goroutines because the NotifyBulk method would return the actual set of chans that were mutated which can then just be diffed directly against the chans being watched in the thread that writes to the FSM and each of their subscribers notified without any background goroutines at all.

That said, as I mentioned [here](https://github.com/hashicorp/consul/issues/4984#issuecomment-445968427) I actually built this today, but I don't really think it's a great option for Consul (or MemDB) because it ties the blocking too tightly with MemDB/iradix internals.

Please see my alternate variation on your hashicorp/consul#5050 here: hashicorp/consul#5081.

I'm not really sure if there is more left to optimise here without major changes to the data structure and API. We could increase `aFew` but it seems incremental and very variable whether it would really help depending on CPU specs and workload. I think hashicorp/consul#5081 is the right approach for Consul and any further improvements probably need either much more invasive changes to mem-db and iradix, or a redesign of how Consul actually manages watching for updates (e.g. multicasting updates to interested clients as they happen rather than through watching the memdb).

On that basis I think I'll close this issue for now because I don't see a specific path forward that is clearly good enough to warrant big changes to this lib right now. Happy to reconsider if anyone has a concrete proposal and/or time to experiment and get some good scientific basis for tuning differently.
